spring.application.name=api-gateway
server.port=8084

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#############################
# Gateway Routes
#############################

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Page Service
spring.cloud.gateway.routes[1].id=page-service
spring.cloud.gateway.routes[1].uri=lb://PAGE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pages/**

# User Service
spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/users/**

# Admin Service
spring.cloud.gateway.routes[3].id=admin-service
spring.cloud.gateway.routes[3].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/admin/**
